### ISSUE TITLE
The genome used to be compared can only include one chromosome 

### ISSUE THREAD

**Issue by liufy1** [SAMtoBAM/MUMandCo#1]
hello!
       when I use MUMandCo to detect SVs between two different genomes of Arabidopsis thaliana，It shows no SV; and only when I separate the genome of Arabidopsis thaliana to 5 chromosomes , and detect SV between two chromosomes, for example chr1 (in the first Arabidopsis thaliana) and chr1(in the second Arabidopsis thaliana) ,  It works. So I wonder whether the genome used to be compared can only include one chromosome?

**Comment by SAMtoBAM** [comment]
Apologies, 
I had no notification that there was an issue opened!
Perhaps this is too late

I'm not sure what is happening here as there is no need to seperate the genome into individual chromosomes
Can I have a test with your genomes on my side?

**Comment by SAMtoBAM** [comment]
@liufy1 
Is this still an issue?
