### ISSUE TITLE
How to understanding the inversion result? 

### ISSUE THREAD

**Issue by luca-Wang** [SAMtoBAM/MUMandCo#10]
Hi,

I am using the MUMandCo to call the inversions between two genomes, but when I check the result I wondering to kown how to understand the inversion events?

**1. The output_ref.delta_filter.coords** : 
[S1] | [E1] | [S2] | [E2] | [LEN 1] | [LEN 2] | [% IDY] | [LEN R] | [LEN Q] | [COV R] | [COV Q] | [FRM] | [TAGS] |   |  
11,665,052 | 11,665,723 | 9,931,117 | 9,931,788 | 672 | 672 | 99.85 | 80,049,271 | 78,190,240 | 0 | 0 | 1 | 1 | Superscaffold1 | Superscaffold1
11,672,615 | 11,676,403 | 9,937,388 | 9,941,179 | 3,789 | 3,792 | 99.53 | 80,049,271 | 78,190,240 | 0 | 0 | 1 | 1 | Superscaffold1 | Superscaffold1

**2. grep 'inversion' output.SVs_all.tsv|head -n1**
ref_chr | query_chr | ref_start | ref_stop | size | SV_type | query_start | query_stop
Superscaffold1 | Superscaffold1 | 11,665,723 | 11,672,615 | 6,892 | inversion | 9,931,788 | 9,937,388

3. The result in output_ref.delta_filter.coords shows 11,665,723-11,672,615 was not aligned, but the output.SVs_all.tsv shows it was a inversion ?

details was in the attachment:
[MUMandCo_inversion_check.xlsx](https://github.com/SAMtoBAM/MUMandCo/files/5865292/MUMandCo_inversion_check.xlsx)

Thanks in advance!

**Comment by SAMtoBAM** [comment]
Hi there, 
Could you please send me the MUM&Co output and the alignment files if possible

**Comment by luca-Wang** [comment]
[output_upload.zip](https://github.com/SAMtoBAM/MUMandCo/files/5941858/output_upload.zip)

Hi, here is the  MUM&Co output and the alignment files

**Comment by SAMtoBAM** [comment]
Thank you

So only in the output_query.delta_filter.coords do I not find an alignment
but looking at output_ref.delta_filter.coords I can find the inverted alignment

> `
> 11665052	11665723	9931117	9931788	672	672	99.85	80049271	78190240	0	0	1	1	Superscaffold1	Superscaffold1
> 
> 11669933	11671486	23790354	23788803	1554	1552	99.74	80049271	78190240	0	0	1	-1	Superscaffold1	Superscaffold1
> 
> 11669933	11671488	44374949	44376508	1556	1560	99.04	80049271	78190240	0	0	1	1	Superscaffold1	Superscaffold1
> 
> 11672615	11676403	9937388	9941179	3789	3792	99.53	80049271	78190240	0	0	1	1	Superscaffold1	Superscaffold1
> `

It seems another section of 'superscaffold1' aligns to a gap in the alignment. Considering both genomes contain the gap in the alignment, which looks like an equivalent insertion and deletion at the same sight, MUM&Co has found this inverted alignment with the best alignment quality and decided it may explain the insertion-deletion problem. It does this as I have found in many cases the global alignment 'coordsg' can remove inverted alignments creating these insertion-deletion calls, and if an inverted alignment is found in the region is calls an inversion. 
In this case the inverted fragment comes from another region of superscaffold1 and is smaller than the gap, so it seems unlikely to be a real call, but, as indicated in the alignment, this region has something to possibly investigate.
If the scaffolding was performed by reference alignment, perhaps you could try running MUM&Co prior to scaffolding and see what happens?
The genome appears highly repetitive too which is always going to create some difficulties

Hope this helps
