### ISSUE TITLE
SV call from multiple genomes comparison

### ISSUE THREAD

**Issue by rthapa1** [SAMtoBAM/MUMandCo#11]
Hi, Is it possible to call SV by comparing  multiple genome with reference genome? The script can take only single query genome at a time.
bash mumandco.sh -r ./yeast.tidy.fa -q ./yeast_tidy_DEL100.fa -g 12500000 -o DEL100_test

**Comment by SAMtoBAM** [comment]
Hello,
The assumption is that there are 1-1 alignments between the query and reference. This is based on the alignment, filtering and chromosome-contig matching processes.
However you could run the script multiple times  whilst only changing the query genome and the results would be the same. Would that be sufficient?

**Comment by rthapa1** [comment]
Thank you. That sounds good but can we merge the final outputs across different comparison to get single output file?

**Comment by SAMtoBAM** [comment]
You sure can.
The reference coordinates are of course comparable across the different outputs/runs (assuming you keep the reference the same) so can be used to remove redundancy. Most calls should contain exact bp matches for both the beginning and end of an event in the case of the same SV.

**Comment by rthapa1** [comment]
Thanks a lot.
I wonder if there is a way to check if the assembly is correct. I checked the assembly with QUAST and the genome is complete. But I don't know how to check if the genome assembly is correct. I am working with bacterial genomes. 
I used canu and Nanopore sequence reads for de novo genome assembly of some strains of bacteria and later polished the genome with Pilon. The bacterial genome is circular and haploid but Canu doesn't assemble it as circular genome so there is different arrangement of some parts of contigs compared to reference genome as shown in attached figure. Do you have any idea if this affects the follow up SV call with MUMandCo?
<img width="1151" alt="Screen Shot 2020-12-17 at 11 20 34 AM" src="https://user-images.githubusercontent.com/61608522/106526815-3d48bc80-64b4-11eb-9f23-009252bee95a.png">

**Comment by SAMtoBAM** [comment]
You can check if the assemblies are correct in many ways such as comparing two assemblies in terms of SNPs, looking at a global dotplot. One way MUM&Co can be used would be to get two de-novo assemblies from different assemblers, that both look to be complete and run each individually against your reference and check that all SVs are found in both assemblies. 

The only difference I see between the two assemblies in the image you uploaded is that they do not begin from the same point, If I understand it correctly. I am not sure how this will impact MUM&Co. I have tested it only against linear chromosomes. 
Could you run it and check?

**Comment by rthapa1** [comment]
Thank you, I will check it.
I wonder if we need to have same start point of genome assembly across multiple genomes to get SV using Mum&Co.

**Comment by SAMtoBAM** [comment]
Yes I understood that. As I said, I am unsure exactly how MUM&Co will interpret the alignment of circular genomes that do not begin from the same point.
You can quickly run MUM&Co on your genome and have a look at the output.
I would be interested in what happens

**Comment by SAMtoBAM** [comment]
Did you manage to get some results§
