### ISSUE TITLE
syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by WenChangYu** [SAMtoBAM/MUMandCo#17]
Hello,

When I run bash mumandco_v3.7.sh according to this website on ubuntu, but I met the following error:

mumandco_v3.7.sh: line 7: syntax error near unexpected token 'newline'
mumandco_v3.7.sh: line 7: '<!DOCTYPE html>'

<img width="401" alt="微信截图_20210920115141" src="https://user-images.githubusercontent.com/25794743/133956019-cf32eaac-f879-4586-9043-631aabc7ea83.png">

Any help?

Thanks in advance.

**Comment by SAMtoBAM** [comment]
Hi there, 
Can you send me your actual command used? and was their any output?

I don't have any error messages encoded so this is purely a bash error message

Thanks!

**Comment by SAMtoBAM** [comment]
Ok well I am stumped essentially.
I also have no idea where the doctype error is coming from

Would you be able to send me the smallest chromosome (or two syntenic contigs/large fragments) from the ref and query genome?
I will run a test on my end

**Comment by WenChangYu** [comment]
Please see the attach file in fasta formate.

**Comment by SAMtoBAM** [comment]
Well I found the issue
The file you have called mumandco_v3.7.sh is not the script
I think you have downloaded the html code behind the webpage.
Can you try downloading the script again

**Comment by WenChangYu** [comment]
I download the script, and it works.

Thanks so much!
