### ISSUE TITLE
Return to 'multiple threads?' closed issue

### ISSUE THREAD

**Issue by davidaray** [SAMtoBAM/MUMandCo#18]
Several months ago, you and I corresponded about the need for multithreading and it seems you took that opportunity to generate a new version. 

I've come back to this after a while and have found that this new version isn't working for me. I'm getting some very strange errors that I have no idea how to deal with. 

These new errors seem to stem from this issue that comes up four times during a run of the test data. 

g++: error: /opt/ohpc/pub/compiler/gcc/5.4.0/lib/../lib64/libstdc++.so: No such file or directory
g++: error: /opt/ohpc/pub/compiler/gcc/5.4.0/lib/../lib64/libstdc++.so: No such file or directory
g++: error: /opt/ohpc/pub/compiler/gcc/5.4.0/lib/../lib64/libstdc++.so: No such file or directory
g++: error: /opt/ohpc/pub/compiler/gcc/5.4.0/lib/../lib64/libstdc++.so: No such file or directory

I've done some troubleshooting and I think I've narrowed it down to these lines:

	$SHOWCOORDS -T -r -c -l -d -g ""$prefix"_ref".delta_filter > ""$prefix"_ref".delta_filter.coordsg
	$SHOWCOORDS -T -r -c -l -d ""$prefix"_ref".delta_filter > ""$prefix"_ref".delta_filter.coords

	$NUCMER --threads ${threads} --maxmatch --nosimplify -p ""$prefix"_query" $query_assembly $reference_assembly
	$DELTAFILTER -m ""$prefix"_query".delta > ""$prefix"_query".delta_filter
	$SHOWCOORDS -T -r -c -l -d -g ""$prefix"_query".delta_filter > ""$prefix"_query".delta_filter.coordsg
	$SHOWCOORDS -T -r -c -l -d ""$prefix"_query".delta_filter > ""$prefix"_query".delta_filter.coords

There are four $SHOWCOORDS commands. 

Any idea what might be going on here?

This could be a 'my HPCC' problem and likely is but I thought I'd ask.

_Originally posted by @davidaray in https://github.com/SAMtoBAM/MUMandCo/issues/12#issuecomment-925374476_

**Comment by SAMtoBAM** [comment]
Hi there!
Yes, I ended up just adding the multi-threaded option to the base version and therefore require MUMmer4 installation for any use.
I was trying to hold onto MUMer3 utility but your issue pushed me to drop it

So this new issue will come from one of the required tools, and yes it might be MUMmer4
Can you try running a 1.nucmer , 2.delta-filter, 3.show-coords pipeline like above on a small test genome?

**Comment by davidaray** [comment]
Yes, I ran it line by line and it was $SHOWCOORDS that triggers the problem. 

The path I assigned seems fine. It at least tries to call show-coords.

Maybe there's a library missing somewhere. delta-filter and nucmer run to completion with no problem on the test data.

**Comment by SAMtoBAM** [comment]
I would just try install mummer4 again then
Apparently there is a [bioconda installation](https://anaconda.org/bioconda/mummer4) now
I just created a conda env with it and it seems to be working well

Can you give that a whirl?

**Comment by davidaray** [comment]
I'd also asked our HPCC support folk and they gave me non-conflicting answer. Ours is made up of multiple systems and it turns out mummer had been compiled on one but not the other. I was trying to use the other. 

I've since recompiled on my target system and it passed the SHOWCOORDS step this time.

Another question, probably premature. My eventual goal is to identify differential SINE insertions and I see in the documentation this:

MUMmer4 is now required due to the hard wired thread option not available during alignment with MUMmer3
Additionally there is an option to search for insertion and deletion events in the reference in order to label them as either mobile or novel events.
This requires BLAST installation.
In order to use this feature, edit the bash script to change 'blast_step="no"' to 'yes'

I get that blast would be used but wouldn't I need a query file with my SINE consensus sequences for blast to use as a reference? I don't see that anywhere in the script but I could be missing it.

**Comment by SAMtoBAM** [comment]
> I've since recompiled on my target system and it passed the SHOWCOORDS step this time.

Great, i'll close this now

> I get that blast would be used but wouldn't I need a query file with my SINE consensus sequences for blast to use as a reference? I don't see that anywhere in the script but I could be missing it.

So the BLAST system takes a little long as it searches, one by one, for each sequence involved in the SV within the reference or query genome. For example, if the SV is a deletion it will look for that same sequence within the query genome to see if it occurs somewhere else, or if it is an insertion it will look in the reference to see if it existed beforehand. It is not very sophisticated, I forget the thresholds set for considering it a match (they could definitely be optimised) but for me it made it easy to separate out very frequent TY insertions/deletions from other novel events. 
I think you would be better off taking the TSV file containing the sequences, creating a database from insertion events and searching for your SINE consensus instead.
