### ISSUE TITLE
--threads has no default value

### ISSUE THREAD

**Issue by hhuili** [SAMtoBAM/MUMandCo#20]
Hi,

When I don't use the `-t` parameter, the bash script will report an error. Which should be that the `${threads}` does not have a default value.

e.g.
https://github.com/SAMtoBAM/MUMandCo/blob/14f38bdb3ee7a51a52da966f25a7a61f6a4b2b30/mumandco_v3.7.sh#L89

**Comment by SAMtoBAM** [comment]
Very true, 
I have simply added a default threads value of 1 now
