### ISSUE TITLE
support for other alingment formats

### ISSUE THREAD

**Issue by aseetharam** [SAMtoBAM/MUMandCo#23]
Hello,

Thanks for making this package! We were trying to use MUMandCo with another aligner (which we think is better than MUMmer) and wondered if it can support other alignment formats? Specifically, standard formats like `maf`

Thanks,

**Comment by SAMtoBAM** [comment]
Hi there, 

At the moment I have no intent on supporting other alignment formats (or simply time to do so)

Apologies and thanks for understanding
