### ISSUE TITLE
Can MUMandCo detect intrachromosomal translocation

### ISSUE THREAD

**Issue by liufy11** [SAMtoBAM/MUMandCo#3]
I want to detect SV between two samples on  chromosome A09 . (only one chromosome).

a error occurs like this:
cat: '*.transloc_pairing': No such file or directory
rm: cannot remove '*.transloc_pairing': No such file or directory

and there is no translocation been detected. 
so I wonder whether MUMandCo can detect intrachromosomal translocation.

**Comment by SAMtoBAM** [comment]
@liufy11 
is this still an issue?
The error as I have tracked down will no longer appear in the latest version of the script
However it doesn't change the output and still intrachromosomal translocations appear as an insertion and deletion
