### ISSUE TITLE
Error finding translocation fragments

### ISSUE THREAD

**Issue by elcortegano** [SAMtoBAM/MUMandCo#6]
I got an error when running the example provided in the documentation. Under the line saying "**Finding translocation fragments**", the following error message appears:

    cat: '*.transloc_pairing': No such file or directory
    rm: cannot remove '*.transloc_pairing': No such file or directory

The program does not stop there but continue running, although I'm not sure if the output is correct, given the above message, and that the total number of SV is 101, but 100 deletions are reported.

    DEL100_test  Total SVs  = 101
    DEL100_test  Deletions  = 100
    DEL100_test  Insertions  = 0
    DEL100_test  Duplications  = 0
    DEL100_test  Inversions  = 0
    DEL100_test  Translocations  = 0

Is this output normal? what does mean that `*.transloc_pairing` is missing?

**Comment by SAMtoBAM** [comment]
Hi there, 

In fact, all has run well! 

The 'error' about the *.translocation_pairing' file is fine, nothing to worry about, it's just a message that appears in the absence of translocations.
I have put a little check make sure these files exist before proceeding so the error should disappear

And the error in the total count is just a problem with an extra line, seems to appear purely in the case of the deletion test set
I have added just a quick filter for empty lines and so the total comes down to 100

Can you try out 2.4.2 ?

Thanks

**Comment by elcortegano** [comment]
It is more clear now, and works great, thank you!
