### ISSUE TITLE
Variable number of variants found over runs

### ISSUE THREAD

**Issue by elcortegano** [SAMtoBAM/MUMandCo#7]
I have a reproducibility concern, as I've found that when I repeat the same analysis (i.e. same input and options), the number of variants found may vary. I attach input files [reference.txt](https://github.com/SAMtoBAM/MUMandCo/files/5282181/reference.txt) and [query.txt](https://github.com/SAMtoBAM/MUMandCo/files/5282179/query.txt) (file extension change required). I run MUM&Co as:

    bash mumandco_v2.4.2.sh -r reference.fa -q query.fa -g 110000000 -o test

There is a duplication variant, that sometimes appears in the output file, and sometimes does not. The line corresponding to the variant is:

    chromosome_2:3065688-8669002(+)	ctg10:50000-5629894(+)	5595283	5597834	2551	duplication	5569429	5577054

Why this behaviour? is it normal? This suggest me that there are some stochastics involved in the process. Should a seed parameter be made available?

Thank you

**Comment by SAMtoBAM** [comment]
Hi @elcortegano 

I have oddly been able to reproduce the same problem on my end
Off the bat I have no idea what is causing this as there should not be any stochasticity...

I have traced the problem back to MUMmer...
If you look at the alignment files all produced by MUMmer using it's tools, specifically the 'test_query.delta_filter.coordsg' file
You will notice that the last alignment differs in position in the reference...
So any randomness comes from MUMmer

but the outcome is that the duplication is filtered out
Not sure I can do more than that unfortunately

**Comment by elcortegano** [comment]
To me it works for now knowing this. Thank you for the clarification!
