### ISSUE TITLE
No insertions but many deletions found

### ISSUE THREAD

**Issue by ASLeonard** [SAMtoBAM/MUMandCo#9]
Hi,
I've tried running this with the latest version (v2.4.2) and Mummer4 on a  ~3gb assembly. I also tried running it with Assemblytics on the prefix_ref.delta file (it matches their ordering of nucmer arguments). The MUMandCo script reported 0 insertions while Assemblytics found several thousand, as summarised below.

SV | count (mum&co) | count (Assemblytics)
--- |--- | ---
Total_SVs  |     8563 |
Deletions    |   6794 | 4304
Insertions    |  0 | 4583
Duplications |   479 | 
Inversions     | 0 |
Translocations | 1290 |

The assembly **is** larger than the reference (3 vs 2.7gb), but still these results are unexpected. Do you have any idea as to why there are 0 reported insertions, or any intermediate files I should keep to check this out further?

Thanks,
Alex

**Comment by SAMtoBAM** [comment]
Hi @ASLeonard 

Did you let MUM&Co perform the alignment? or give it a delta file?
It appears that the reciprocal alignment wasn't performed or used...

**Comment by ASLeonard** [comment]
Hi,
Yes the script performed the alignment, and made 1.2gb and .8gb for the prefix_ref.delta and prefix_query.delta files. Similarly, the filter/coords/coordsg were all generated correctly it seems.

**Comment by SAMtoBAM** [comment]
Very strange!
Something rather fundamental has gone wrong which I would say is down to the alignment, I can't say what though...

Is it possible to send me your genomes?
If it is too big, perhaps just a single chromosome and it's associated contigs?

**Comment by SAMtoBAM** [comment]
Hi @ASLeonard 
Is this still an issue?

**Comment by ASLeonard** [comment]
Sorry, got sidetracked.

Even single chromosome is too large to upload, so I can email or find a different fileshare depending on what you find easier.

**Comment by SAMtoBAM** [comment]
No worries, 

you can email me files at samuel.a.odonnell@gmail.com

**Comment by ASLeonard** [comment]
After rerunning from scratch, everything appears to be working now. Now inversions and insertions are correctly being found. I think there may have been an early termination to the filtering step, and then the script continued as normal with incomplete filter files.

Thanks for taking a look!
